<?php

namespace bp\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Api_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Api_usersRepository extends EntityRepository
{
}
